spring.application.name=resource-server
server.port=8081

## É a URL do "issuer" (emissor) do token JWT.
## localhost:8087 ? onde o Keycloak está rodando
## /realms/master ? o realm (tipo um "ambiente" de autenticação)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8087/realms/master